name: CI/CD
on:
  push:
    branches: [ main ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          cd src/
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          cd src/
          python -m unittest discover tests/
        # - name: Style Check
        # run: |
        #   cd src/
        #   flake8 --ignore=E402 .


  deployment:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          host: 54.144.76.35
          username: test
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            rm -rf t4test
            git clone https://github.com/jimmyread-99/t4test
            apt-get install python3-venv
            cd src/
            python3.8 -m venv /home/test/t4test/src/venv
            source /home/test/t4test/src/venv/bin/activate
            /home/test/t4test/src/venv/bin/pip3.8 install -r /home/test/t4test/src/requirements.txt